#!/bin/sh

type=${0##*/}
hdir=$0.d
orig=${0%/*}/../.git/hooks/$type

exec 1>&2

for hlet in $hdir/???*; do
    case $hlet in
        *~|*.swp)
            continue
            ;;
        [0-9][0-9]-*)
            ;;
    esac
    if [ ! -x $hlet ]; then
        continue
    fi

    echo "<checking $type/${hlet##*/}>"
    $hlet
    r=$?
    if [ $r != 0 ]; then
        exit $r
    fi
done

if [ -x $orig ]; then
    echo "<checking .git/hooks/$type>"
    $orig
    exit $?
fi
