apiVersion: v1
kind: ConfigMap
metadata:
  name: cri-resmgr-config
  namespace: kube-system
data:
  #
  # default confguration, used by any node without a node-specific configuration
  #
  default: |
    topology-aware:
      PinCPU: true
      PinMemory: true
      PreferIsolatedCPUs: true
      PreferSharedCPUs: false
    static:
      RelaxedIsolation: true
      Rdt: auto
    stp:
      config:
        # This is an example configuration file for the builtin cmk policy
        # The imaginary example system here consists of 4 sockets, 4 cores (8
        # multithreaded CPUs)
        pools:
          exclusive:
            # 6 exclusive cores, 3 on sockets 1, 2 and 3 each
            cpuLists:
            - Cpuset: 8,9
              Socket: 1
            - Cpuset: 10,11
              Socket: 1
            - Cpuset: 16,17
              Socket: 2
            - Cpuset: 18,19
              Socket: 2
            - Cpuset: 24,25
              Socket: 3
            - Cpuset: 26,27
              Socket: 3
            exclusive: true
          shared:
            # 2 cores in shared pool, all on socket 1
            cpuLists:
            - Cpuset: 12,13,14,15
              Socket: 1
            exclusive: false
          infra:
            # Rest of cores designated to infra pool
            cpuLists:
            - Cpuset: 0,1,2,3,4,5,6,7
              Socket: 0
            - Cpuset: 20,21,22,23
              Socket: 2
            - Cpuset: 28,29,30,31
              Socket: 3
            exclusive: false
    rdt:
      config:
        # Common options
        options:
          l3:
            optional: true
          # If l3code or l3data is NOT set to optional CDP must be enabled in
          # the system in case 'l3codeschema' and/or 'l3dataschema' are specified
          # in the groups below
          l3code:
            optional: true
          l3data:
            optional: true
          mb:
            optional: true
        # This example config specifies three RDT classes (or resctrl groups) with L3
        # CAT configured
        resctrlGroups:
          Guaranteed:
            l3schema:
              all: "100%"
        # Specify CacheId (typically correspons CPU socket) specific setting
        #      1: "80%"
        # MBA (Memory Bandwidth Allocation)
        #    mbschema:
        #      all: 100
        #      1-3: 80
          Burstable:
            l3schema:
              all: "66%"
            # Separate schema for L3 code and data paths specified
            l3codeschema:
              all: "100%"
            l3dataschema:
              all: "50%"
        # MBA (Memory Bandwidth Allocation)
        #    mbschema:
        #      all: 66
          BestEffort:
            l3schema:
              all: "33%"
        # MBA (Memory Bandwidth Allocation)
        #    mbschema:
        #      all: 33
  #
  # node-specific configuration, used by nodes with a matching name
  #
  cl0-slave1: |
    topology-aware:
      PinCPU: true
      PinMemory: true
      PreferIsolatedCPUs: true
      PreferSharedCPUs: false
    static:
      RelaxedIsolation: true
      Rdt: auto
    stp:
      config:
        pools:
          exclusive:
            # 6 exclusive cores, 3 on sockets 1, 2 and 3 each
            cpuLists:
            - Cpuset: 8,9
              Socket: 1
            - Cpuset: 10,11
              Socket: 1
            - Cpuset: 16,17
              Socket: 2
            - Cpuset: 18,19
              Socket: 2
            - Cpuset: 24,25
              Socket: 3
            - Cpuset: 26,27
              Socket: 3
            exclusive: true
          shared:
            # 2 cores in shared pool, all on socket 1
            cpuLists:
            - Cpuset: 12,13,14,15
              Socket: 1
            exclusive: false
          infra:
            # Rest of cores designated to infra pool
            cpuLists:
            - Cpuset: 0,1,2,3,4,5,6,7
              Socket: 0
            - Cpuset: 20,21,22,23
              Socket: 2
            - Cpuset: 28,29,30,31
              Socket: 3
            exclusive: false
    rdt:
      config:
        options:
          l3:
            optional: true
          l3code:
            optional: true
          l3data:
            optional: true
          mb:
            optional: true
        resctrlGroups:
          Guaranteed:
            l3schema:
              all: "100%"
          Burstable:
            l3schema:
              all: "66%"
            l3codeschema:
              all: "100%"
            l3dataschema:
              all: "50%"
          BestEffort:
            l3schema:
              all: "33%"
