#
# This example creates 3 ConfigMaps:
#  - cri-resmgr-config.default: the default configuration
#  - cri-resmgr-config.group.foo: the configuration for nodes in group foo
#  - cri-resmgr-config.node.cl0-slave1: the configuration for node cl0-slave1
#
# You can assign nodes to group foo using the command
#   kubectl label --overwrite node $NODE_NAME cri-resource-manager.intel.com/group=foo
#
# You can remove nodes from group foo using the command
#   kubectl label node $NODE_NAME cri-resource-manager.intel.com/group-
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: cri-resmgr-config.default
  namespace: kube-system
data:
  policy: |+
    Active: topology-aware
    AvailableResources:
      cpu: cpuset:0-63
    ReservedResources:
      cpu: cpuset:0-1
    topology-aware:
      PinCPU: true
      PinMemory: true
      PreferIsolatedCPUs: true
      PreferSharedCPUs: false
    static:
      RelaxedIsolation: true
    static-pools:
      # Filesystem path to legacy configuration directory structure
      ConfDirPath: "/etc/cmk"
      # Filesystem path to legacy configuration file
      ConfFilePath: ""
      # Whether to create CMK node label
      LabelNode: false
      # Whether to create CMK node taint
      TaintNode: false
      # Pool configuration.
      # The imaginary example system below consists of 4 sockets, 4 cores, 2
      # threads each.
      pools:
        exclusive:
          # 6 exclusive cores, 3 on sockets 1, 2 and 3 each
          cpuLists:
          - Cpuset: 8,9
            Socket: 1
          - Cpuset: 10,11
            Socket: 1
          - Cpuset: 16,17
            Socket: 2
          - Cpuset: 18,19
            Socket: 2
          - Cpuset: 24,25
            Socket: 3
          - Cpuset: 26,27
            Socket: 3
          exclusive: true
        shared:
          # 2 cores in shared pool, all on socket 1
          cpuLists:
          - Cpuset: 12,13,14,15
            Socket: 1
          exclusive: false
        infra:
          # Rest of cores designated to infra pool
          cpuLists:
          - Cpuset: 0,1,2,3,4,5,6,7
            Socket: 0
          - Cpuset: 20,21,22,23
            Socket: 2
          - Cpuset: 28,29,30,31
            Socket: 3
          exclusive: false
  rdt: |+
    # Common options
    options:
      # One of Full, Discovery or Disabled
      mode: Full
      # Set to true to disable creation of monitoring groups
      monitoringDisabled: false
      l3:
        # Make this false if L3 CAT must be available
        optional: true
      mb:
        # Make this false if MBA must be available
        optional: true

    # Configuration of classes
    partitions:
      exclusive:
        # Allocate 60% of all L3 cache to the "exclusive" partition
        l3Allocation: "60%"
        mbAllocation: ["100%"]
        classes:
          Guaranteed:
            # Allocate all of the partitions cache lines to "Guaranteed"
            l3Allocation: "100%"
      shared:
        # Allocate 40% L3 cache IDs to the "shared" partition
        # These will NOT overlap with the cache lines allocated for "exclusive" partition
        l3Allocation: "40%"
        mbAllocation: ["50%"]
        classes:
          Burstable:
            # Allow "Burstable" to use all cache lines of the "shared" partition
            l3Allocation: "100%"
          BestEffort:
            # Allow "Besteffort" to use only half of the L3 cache # lines of the "shared" partition.
            # These will overlap with those used by "Burstable"
            l3Allocation: "50%"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cri-resmgr-config.group.foo
  namespace: kube-system
data:
  policy: |+
    Active: topology-aware
    AvailableResources:
      cpu: cpuset:0-63
    ReservedResources:
      cpu: cpuset:0-1
    topology-aware:
      PinCPU: true
      PinMemory: false
      PreferIsolatedCPUs: false
      PreferSharedCPUs: false
    static:
      RelaxedIsolation: true
    static-pools:
      # This is an example configuration for static-pools policy.
      # The imaginary example system here consists of 4 sockets, 4 cores, 2 threads each.
      pools:
        exclusive:
          # 6 exclusive cores, 3 on sockets 1, 2 and 3 each
          cpuLists:
          - Cpuset: 8,9
            Socket: 1
          - Cpuset: 10,11
            Socket: 1
          - Cpuset: 16,17
            Socket: 2
          - Cpuset: 18,19
            Socket: 2
          - Cpuset: 24,25
            Socket: 3
          - Cpuset: 26,27
            Socket: 3
          exclusive: true
        shared:
          # 2 cores in shared pool, all on socket 1
          cpuLists:
          - Cpuset: 12,13,14,15
            Socket: 1
          exclusive: false
        infra:
          # Rest of cores designated to infra pool
          cpuLists:
          - Cpuset: 0,1,2,3,4,5,6,7
            Socket: 0
          - Cpuset: 20,21,22,23
            Socket: 2
          - Cpuset: 28,29,30,31
            Socket: 3
          exclusive: false
  rdt: |+
    # Common options
    options:
      # One of Full, Discovery or Disabled
      mode: Full
      # Set to true to disable creation of monitoring groups
      monitoringDisabled: false
      l3:
        # Make this false if L3 CAT must be available
        optional: true
      mb:
        # Make this false if MBA must be available
        optional: true

    # Configuration of classes
    partitions:
      exclusive:
        # Allocate 60% of all L3 cache to the "exclusive" partition
        l3Allocation: "60%"
        mbAllocation: ["100%"]
        classes:
          Guaranteed:
            # Allocate all of the partitions cache lines to "Guaranteed"
            l3Allocation: "100%"
      shared:
        # Allocate 40% L3 cache IDs to the "shared" partition
        # These will NOT overlap with the cache lines allocated for "exclusive" partition
        l3Allocation: "40%"
        mbAllocation: ["50%"]
        classes:
          Burstable:
            # Allow "Burstable" to use all cache lines of the "shared" partition
            l3Allocation: "100%"
          BestEffort:
            # Allow "Besteffort" to use only half of the L3 cache # lines of the "shared" partition.
            # These will overlap with those used by "Burstable"
            l3Allocation: "50%"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cri-resmgr-config.node.cl0-slave1
  namespace: kube-system
data:
  policy: |+
    Active: topology-aware
    AvailableResources:
      cpu: cpuset:0-63
    ReservedResources:
      cpu: cpuset:0-1
    topology-aware:
      PinCPU: false
      PinMemory: true
      PreferIsolatedCPUs: false
      PreferSharedCPUs: false
    static:
      RelaxedIsolation: true
    static-pools:
      # This is an example configuration for static-pools policy.
      # The imaginary example system here consists of 4 sockets, 4 cores, 2 threads each.
      pools:
        exclusive:
          # 6 exclusive cores, 3 on sockets 1, 2 and 3 each
          cpuLists:
          - Cpuset: 8,9
            Socket: 1
          - Cpuset: 10,11
            Socket: 1
          - Cpuset: 16,17
            Socket: 2
          - Cpuset: 18,19
            Socket: 2
          - Cpuset: 24,25
            Socket: 3
          - Cpuset: 26,27
            Socket: 3
          exclusive: true
        shared:
          # 2 cores in shared pool, all on socket 1
          cpuLists:
          - Cpuset: 12,13,14,15
            Socket: 1
          exclusive: false
        infra:
          # Rest of cores designated to infra pool
          cpuLists:
          - Cpuset: 0,1,2,3,4,5,6,7
            Socket: 0
          - Cpuset: 20,21,22,23
            Socket: 2
          - Cpuset: 28,29,30,31
            Socket: 3
          exclusive: false
  rdt: |+
    # Common options
    options:
      # One of Full, Discovery or Disabled
      mode: Full
      # Set to true to disable creation of monitoring groups
      monitoringDisabled: false
      l3:
        # Make this false if L3 CAT must be available
        optional: true
      mb:
        # Make this false if MBA must be available
        optional: true

    # Configuration of classes
    partitions:
      exclusive:
        # Allocate 60% of all L3 cache to the "exclusive" partition
        l3Allocation: "60%"
        mbAllocation: ["100%"]
        classes:
          Guaranteed:
            # Allocate all of the partitions cache lines to "Guaranteed"
            l3Allocation: "100%"
      shared:
        # Allocate 40% L3 cache IDs to the "shared" partition
        # These will NOT overlap with the cache lines allocated for "exclusive" partition
        l3Allocation: "40%"
        mbAllocation: ["50%"]
        classes:
          Burstable:
            # Allow "Burstable" to use all cache lines of the "shared" partition
            l3Allocation: "100%"
          BestEffort:
            # Allow "Besteffort" to use only half of the L3 cache # lines of the "shared" partition.
            # These will overlap with those used by "Burstable"
            l3Allocation: "50%"
  dump: |+
    Config: full:.*,short:.*Stop.*,off:.*List.*
    File: /tmp/cri-selective-debug.dump
  logger: |+
    Debug: resource-manager,cache
