// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetNodeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodeRequest) Reset()         { *m = GetNodeRequest{} }
func (m *GetNodeRequest) String() string { return proto.CompactTextString(m) }
func (*GetNodeRequest) ProtoMessage()    {}
func (*GetNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_c34572713b59108b, []int{0}
}
func (m *GetNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeRequest.Unmarshal(m, b)
}
func (m *GetNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeRequest.Marshal(b, m, deterministic)
}
func (dst *GetNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeRequest.Merge(dst, src)
}
func (m *GetNodeRequest) XXX_Size() int {
	return xxx_messageInfo_GetNodeRequest.Size(m)
}
func (m *GetNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeRequest proto.InternalMessageInfo

type GetNodeReply struct {
	Node                 string   `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNodeReply) Reset()         { *m = GetNodeReply{} }
func (m *GetNodeReply) String() string { return proto.CompactTextString(m) }
func (*GetNodeReply) ProtoMessage()    {}
func (*GetNodeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_c34572713b59108b, []int{1}
}
func (m *GetNodeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNodeReply.Unmarshal(m, b)
}
func (m *GetNodeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNodeReply.Marshal(b, m, deterministic)
}
func (dst *GetNodeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNodeReply.Merge(dst, src)
}
func (m *GetNodeReply) XXX_Size() int {
	return xxx_messageInfo_GetNodeReply.Size(m)
}
func (m *GetNodeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNodeReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetNodeReply proto.InternalMessageInfo

func (m *GetNodeReply) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

// JsonPatch holds on JSON patch
type JsonPatch struct {
	Op                   string   `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JsonPatch) Reset()         { *m = JsonPatch{} }
func (m *JsonPatch) String() string { return proto.CompactTextString(m) }
func (*JsonPatch) ProtoMessage()    {}
func (*JsonPatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_c34572713b59108b, []int{2}
}
func (m *JsonPatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JsonPatch.Unmarshal(m, b)
}
func (m *JsonPatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JsonPatch.Marshal(b, m, deterministic)
}
func (dst *JsonPatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JsonPatch.Merge(dst, src)
}
func (m *JsonPatch) XXX_Size() int {
	return xxx_messageInfo_JsonPatch.Size(m)
}
func (m *JsonPatch) XXX_DiscardUnknown() {
	xxx_messageInfo_JsonPatch.DiscardUnknown(m)
}

var xxx_messageInfo_JsonPatch proto.InternalMessageInfo

func (m *JsonPatch) GetOp() string {
	if m != nil {
		return m.Op
	}
	return ""
}

func (m *JsonPatch) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *JsonPatch) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type PatchNodeRequest struct {
	// List of JSON patches to apply on the node
	Patches              []*JsonPatch `protobuf:"bytes,1,rep,name=patches,proto3" json:"patches,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PatchNodeRequest) Reset()         { *m = PatchNodeRequest{} }
func (m *PatchNodeRequest) String() string { return proto.CompactTextString(m) }
func (*PatchNodeRequest) ProtoMessage()    {}
func (*PatchNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_c34572713b59108b, []int{3}
}
func (m *PatchNodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatchNodeRequest.Unmarshal(m, b)
}
func (m *PatchNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatchNodeRequest.Marshal(b, m, deterministic)
}
func (dst *PatchNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatchNodeRequest.Merge(dst, src)
}
func (m *PatchNodeRequest) XXX_Size() int {
	return xxx_messageInfo_PatchNodeRequest.Size(m)
}
func (m *PatchNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PatchNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PatchNodeRequest proto.InternalMessageInfo

func (m *PatchNodeRequest) GetPatches() []*JsonPatch {
	if m != nil {
		return m.Patches
	}
	return nil
}

type PatchNodeReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PatchNodeReply) Reset()         { *m = PatchNodeReply{} }
func (m *PatchNodeReply) String() string { return proto.CompactTextString(m) }
func (*PatchNodeReply) ProtoMessage()    {}
func (*PatchNodeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_c34572713b59108b, []int{4}
}
func (m *PatchNodeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PatchNodeReply.Unmarshal(m, b)
}
func (m *PatchNodeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PatchNodeReply.Marshal(b, m, deterministic)
}
func (dst *PatchNodeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PatchNodeReply.Merge(dst, src)
}
func (m *PatchNodeReply) XXX_Size() int {
	return xxx_messageInfo_PatchNodeReply.Size(m)
}
func (m *PatchNodeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PatchNodeReply.DiscardUnknown(m)
}

var xxx_messageInfo_PatchNodeReply proto.InternalMessageInfo

type UpdateNodeCapacityRequest struct {
	// Name-value map of status.capacity to update
	Capacities           map[string]string `protobuf:"bytes,1,rep,name=capacities,proto3" json:"capacities,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UpdateNodeCapacityRequest) Reset()         { *m = UpdateNodeCapacityRequest{} }
func (m *UpdateNodeCapacityRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateNodeCapacityRequest) ProtoMessage()    {}
func (*UpdateNodeCapacityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_c34572713b59108b, []int{5}
}
func (m *UpdateNodeCapacityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNodeCapacityRequest.Unmarshal(m, b)
}
func (m *UpdateNodeCapacityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNodeCapacityRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateNodeCapacityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNodeCapacityRequest.Merge(dst, src)
}
func (m *UpdateNodeCapacityRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateNodeCapacityRequest.Size(m)
}
func (m *UpdateNodeCapacityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNodeCapacityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNodeCapacityRequest proto.InternalMessageInfo

func (m *UpdateNodeCapacityRequest) GetCapacities() map[string]string {
	if m != nil {
		return m.Capacities
	}
	return nil
}

type UpdateNodeCapacityReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateNodeCapacityReply) Reset()         { *m = UpdateNodeCapacityReply{} }
func (m *UpdateNodeCapacityReply) String() string { return proto.CompactTextString(m) }
func (*UpdateNodeCapacityReply) ProtoMessage()    {}
func (*UpdateNodeCapacityReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_c34572713b59108b, []int{6}
}
func (m *UpdateNodeCapacityReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNodeCapacityReply.Unmarshal(m, b)
}
func (m *UpdateNodeCapacityReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNodeCapacityReply.Marshal(b, m, deterministic)
}
func (dst *UpdateNodeCapacityReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNodeCapacityReply.Merge(dst, src)
}
func (m *UpdateNodeCapacityReply) XXX_Size() int {
	return xxx_messageInfo_UpdateNodeCapacityReply.Size(m)
}
func (m *UpdateNodeCapacityReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNodeCapacityReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNodeCapacityReply proto.InternalMessageInfo

type GetConfigRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigRequest) Reset()         { *m = GetConfigRequest{} }
func (m *GetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*GetConfigRequest) ProtoMessage()    {}
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_c34572713b59108b, []int{7}
}
func (m *GetConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigRequest.Unmarshal(m, b)
}
func (m *GetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigRequest.Marshal(b, m, deterministic)
}
func (dst *GetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigRequest.Merge(dst, src)
}
func (m *GetConfigRequest) XXX_Size() int {
	return xxx_messageInfo_GetConfigRequest.Size(m)
}
func (m *GetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigRequest proto.InternalMessageInfo

type GetConfigReply struct {
	NodeName             string            `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Config               map[string]string `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetConfigReply) Reset()         { *m = GetConfigReply{} }
func (m *GetConfigReply) String() string { return proto.CompactTextString(m) }
func (*GetConfigReply) ProtoMessage()    {}
func (*GetConfigReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_c34572713b59108b, []int{8}
}
func (m *GetConfigReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigReply.Unmarshal(m, b)
}
func (m *GetConfigReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigReply.Marshal(b, m, deterministic)
}
func (dst *GetConfigReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigReply.Merge(dst, src)
}
func (m *GetConfigReply) XXX_Size() int {
	return xxx_messageInfo_GetConfigReply.Size(m)
}
func (m *GetConfigReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigReply proto.InternalMessageInfo

func (m *GetConfigReply) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *GetConfigReply) GetConfig() map[string]string {
	if m != nil {
		return m.Config
	}
	return nil
}

type HealthCheckRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckRequest) Reset()         { *m = HealthCheckRequest{} }
func (m *HealthCheckRequest) String() string { return proto.CompactTextString(m) }
func (*HealthCheckRequest) ProtoMessage()    {}
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_c34572713b59108b, []int{9}
}
func (m *HealthCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckRequest.Unmarshal(m, b)
}
func (m *HealthCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckRequest.Marshal(b, m, deterministic)
}
func (dst *HealthCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckRequest.Merge(dst, src)
}
func (m *HealthCheckRequest) XXX_Size() int {
	return xxx_messageInfo_HealthCheckRequest.Size(m)
}
func (m *HealthCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckRequest proto.InternalMessageInfo

type HealthCheckReply struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckReply) Reset()         { *m = HealthCheckReply{} }
func (m *HealthCheckReply) String() string { return proto.CompactTextString(m) }
func (*HealthCheckReply) ProtoMessage()    {}
func (*HealthCheckReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_c34572713b59108b, []int{10}
}
func (m *HealthCheckReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckReply.Unmarshal(m, b)
}
func (m *HealthCheckReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckReply.Marshal(b, m, deterministic)
}
func (dst *HealthCheckReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckReply.Merge(dst, src)
}
func (m *HealthCheckReply) XXX_Size() int {
	return xxx_messageInfo_HealthCheckReply.Size(m)
}
func (m *HealthCheckReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckReply.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckReply proto.InternalMessageInfo

func (m *HealthCheckReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*GetNodeRequest)(nil), "v1.GetNodeRequest")
	proto.RegisterType((*GetNodeReply)(nil), "v1.GetNodeReply")
	proto.RegisterType((*JsonPatch)(nil), "v1.JsonPatch")
	proto.RegisterType((*PatchNodeRequest)(nil), "v1.PatchNodeRequest")
	proto.RegisterType((*PatchNodeReply)(nil), "v1.PatchNodeReply")
	proto.RegisterType((*UpdateNodeCapacityRequest)(nil), "v1.UpdateNodeCapacityRequest")
	proto.RegisterMapType((map[string]string)(nil), "v1.UpdateNodeCapacityRequest.CapacitiesEntry")
	proto.RegisterType((*UpdateNodeCapacityReply)(nil), "v1.UpdateNodeCapacityReply")
	proto.RegisterType((*GetConfigRequest)(nil), "v1.GetConfigRequest")
	proto.RegisterType((*GetConfigReply)(nil), "v1.GetConfigReply")
	proto.RegisterMapType((map[string]string)(nil), "v1.GetConfigReply.ConfigEntry")
	proto.RegisterType((*HealthCheckRequest)(nil), "v1.HealthCheckRequest")
	proto.RegisterType((*HealthCheckReply)(nil), "v1.HealthCheckReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentClient interface {
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeReply, error)
	PatchNode(ctx context.Context, in *PatchNodeRequest, opts ...grpc.CallOption) (*PatchNodeReply, error)
	UpdateNodeCapacity(ctx context.Context, in *UpdateNodeCapacityRequest, opts ...grpc.CallOption) (*UpdateNodeCapacityReply, error)
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigReply, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckReply, error)
}

type agentClient struct {
	cc *grpc.ClientConn
}

func NewAgentClient(cc *grpc.ClientConn) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeReply, error) {
	out := new(GetNodeReply)
	err := c.cc.Invoke(ctx, "/v1.Agent/GetNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) PatchNode(ctx context.Context, in *PatchNodeRequest, opts ...grpc.CallOption) (*PatchNodeReply, error) {
	out := new(PatchNodeReply)
	err := c.cc.Invoke(ctx, "/v1.Agent/PatchNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) UpdateNodeCapacity(ctx context.Context, in *UpdateNodeCapacityRequest, opts ...grpc.CallOption) (*UpdateNodeCapacityReply, error) {
	out := new(UpdateNodeCapacityReply)
	err := c.cc.Invoke(ctx, "/v1.Agent/UpdateNodeCapacity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigReply, error) {
	out := new(GetConfigReply)
	err := c.cc.Invoke(ctx, "/v1.Agent/GetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckReply, error) {
	out := new(HealthCheckReply)
	err := c.cc.Invoke(ctx, "/v1.Agent/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
type AgentServer interface {
	GetNode(context.Context, *GetNodeRequest) (*GetNodeReply, error)
	PatchNode(context.Context, *PatchNodeRequest) (*PatchNodeReply, error)
	UpdateNodeCapacity(context.Context, *UpdateNodeCapacityRequest) (*UpdateNodeCapacityReply, error)
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigReply, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckReply, error)
}

func RegisterAgentServer(s *grpc.Server, srv AgentServer) {
	s.RegisterService(&_Agent_serviceDesc, srv)
}

func _Agent_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Agent/GetNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_PatchNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).PatchNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Agent/PatchNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).PatchNode(ctx, req.(*PatchNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_UpdateNodeCapacity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNodeCapacityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).UpdateNodeCapacity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Agent/UpdateNodeCapacity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).UpdateNodeCapacity(ctx, req.(*UpdateNodeCapacityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Agent/GetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.Agent/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Agent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNode",
			Handler:    _Agent_GetNode_Handler,
		},
		{
			MethodName: "PatchNode",
			Handler:    _Agent_PatchNode_Handler,
		},
		{
			MethodName: "UpdateNodeCapacity",
			Handler:    _Agent_UpdateNodeCapacity_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _Agent_GetConfig_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _Agent_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_c34572713b59108b) }

var fileDescriptor_api_c34572713b59108b = []byte{
	// 454 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0x37, 0x4d, 0x8b, 0x27, 0x50, 0xac, 0x91, 0x05, 0xae, 0x2b, 0x50, 0xb5, 0x17, 0x72,
	0xc1, 0x52, 0x8a, 0xc4, 0xa7, 0x7a, 0x80, 0xa8, 0x2a, 0x42, 0xa2, 0x42, 0x96, 0xb8, 0x70, 0x41,
	0x8b, 0xb3, 0x34, 0x51, 0x53, 0xef, 0xe2, 0x6c, 0x23, 0xf9, 0xdf, 0x70, 0xe5, 0x57, 0xf0, 0xd7,
	0xd0, 0xec, 0xda, 0xc6, 0xb1, 0x09, 0x52, 0x6f, 0xe3, 0x37, 0x33, 0x6f, 0xe7, 0xcd, 0x1b, 0x83,
	0x2f, 0xf4, 0x22, 0xd1, 0x85, 0x32, 0x0a, 0xd9, 0x7a, 0xc2, 0x03, 0x38, 0x38, 0x97, 0xe6, 0x42,
	0xcd, 0x64, 0x2a, 0x7f, 0xdc, 0xc8, 0x95, 0xe1, 0x1c, 0xee, 0x36, 0x88, 0x5e, 0x96, 0x88, 0xb0,
	0x9b, 0xab, 0x99, 0x8c, 0xbc, 0x63, 0x6f, 0xec, 0xa7, 0x36, 0xe6, 0x67, 0xe0, 0x7f, 0x58, 0xa9,
	0xfc, 0x93, 0x30, 0xd9, 0x1c, 0x0f, 0x80, 0x29, 0x5d, 0xa5, 0x99, 0xd2, 0xd4, 0xa0, 0x85, 0x99,
	0x47, 0xcc, 0x35, 0x50, 0x8c, 0x21, 0x0c, 0xd7, 0x62, 0x79, 0x23, 0xa3, 0x81, 0x05, 0xdd, 0x07,
	0x7f, 0x03, 0x81, 0xa5, 0x68, 0x3d, 0x8f, 0x4f, 0x60, 0x5f, 0x13, 0x26, 0x57, 0x91, 0x77, 0x3c,
	0x18, 0x8f, 0x4e, 0xee, 0x25, 0xeb, 0x49, 0xd2, 0xbc, 0x96, 0xd6, 0x59, 0x9a, 0xbc, 0xd5, 0xac,
	0x97, 0x25, 0xff, 0xe5, 0xc1, 0xe1, 0x67, 0x3d, 0x13, 0x46, 0x12, 0x36, 0x15, 0x5a, 0x64, 0x0b,
	0x53, 0xd6, 0xc4, 0x1f, 0x01, 0x32, 0x07, 0x2d, 0x1a, 0xee, 0xa7, 0xc4, 0xbd, 0xb5, 0x25, 0x99,
	0x36, 0xf5, 0x67, 0xb9, 0x29, 0xca, 0xb4, 0x45, 0x10, 0x9f, 0xc2, 0xfd, 0x4e, 0x1a, 0x03, 0x18,
	0x5c, 0xc9, 0xb2, 0xda, 0x04, 0x85, 0x7f, 0x65, 0xb3, 0x96, 0xec, 0xd7, 0xec, 0xa5, 0xc7, 0x0f,
	0xe1, 0xe1, 0xbf, 0xde, 0x25, 0x19, 0x08, 0xc1, 0xb9, 0x34, 0x53, 0x95, 0x7f, 0x5f, 0x5c, 0xd6,
	0xa6, 0xfc, 0xf4, 0xac, 0x4f, 0x35, 0x48, 0xbe, 0x1c, 0x81, 0x4f, 0x5e, 0x7c, 0xcd, 0xc5, 0x75,
	0x6d, 0xce, 0x1d, 0x02, 0x2e, 0xc4, 0xb5, 0xc4, 0xe7, 0xb0, 0x97, 0xd9, 0xda, 0x88, 0x59, 0xa1,
	0x8f, 0x49, 0xe8, 0x26, 0x41, 0xe2, 0x62, 0xa7, 0xac, 0xaa, 0x8e, 0x5f, 0xc1, 0xa8, 0x05, 0xdf,
	0x4a, 0x51, 0x08, 0xf8, 0x5e, 0x8a, 0xa5, 0x99, 0x4f, 0xe7, 0x32, 0xbb, 0xaa, 0x07, 0x1f, 0x43,
	0xb0, 0x81, 0xd2, 0xe4, 0x21, 0x0c, 0x65, 0x51, 0xa8, 0xa2, 0xe2, 0x75, 0x1f, 0x27, 0xbf, 0x19,
	0x0c, 0xdf, 0x5e, 0xca, 0xdc, 0xe0, 0x04, 0xf6, 0xab, 0x0b, 0x44, 0xac, 0xe6, 0x6e, 0x5d, 0x48,
	0x1c, 0x6c, 0x60, 0xb4, 0xb1, 0x1d, 0x7c, 0x01, 0x7e, 0x73, 0x0c, 0x18, 0x52, 0x41, 0xf7, 0xb0,
	0x62, 0xec, 0xa0, 0xae, 0x31, 0x05, 0xec, 0xfb, 0x80, 0x8f, 0xfe, 0x7b, 0x17, 0xf1, 0xd1, 0xb6,
	0x74, 0x33, 0x4c, 0xb3, 0x6a, 0x37, 0x4c, 0xd7, 0xcf, 0x18, 0xfb, 0x7e, 0xf0, 0x1d, 0x3c, 0x85,
	0x51, 0x6b, 0x59, 0xf8, 0x80, 0x8a, 0xfa, 0x3b, 0x8d, 0xc3, 0x1e, 0x6e, 0xdb, 0xdf, 0xed, 0x7e,
	0x61, 0xeb, 0xc9, 0xb7, 0x3d, 0xfb, 0x73, 0x3f, 0xfb, 0x13, 0x00, 0x00, 0xff, 0xff, 0x39, 0x76,
	0xc1, 0x08, 0xe9, 0x03, 0x00, 0x00,
}
