# pull in base + a minimal set of useful packages
FROM opensuse/leap:15.4 as suse-15.4-build

ARG GO_VERSION=x.yz
ARG GOLICENSES_VERSION
ARG CREATE_USER="build"
ARG USER_OPTIONS=""
ENV PATH /go/bin:/usr/local/go/bin:$PATH

RUN zypper install -y rpm-build \
    kernel-devel gcc \
    git make

ADD http://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz /

RUN tar xf /go${GO_VERSION}.linux-amd64.tar.gz -C "/usr/local" && \
    rm /go${GO_VERSION}.linux-amd64.tar.gz

RUN GOBIN=/go/bin go install github.com/google/go-licenses@${GOLICENSES_VERSION}

RUN [ -n "$CREATE_USER" -a "$CREATE_USER" != "root" ] && \
    useradd -m -s /bin/bash $CREATE_USER $USER_OPTIONS
