#!/bin/bash

WORKFLOWS=".github/workflows/verify.yml"

gomod=$(git diff --cached go.mod | grep '^+go ' | sed 's/^.* //g')
[ -z "$gomod" ] && exit 0

status=0
for wf in $WORKFLOWS; do
    workflow=$(grep 'go-version:' .github/workflows/verify.yml | sed 's/^.*: //')
    if [ "gomod" != "$workflow" ]; then
        echo >&2 "ERROR: inconsistent golang versions, $gomod in go.mod but $workflow in $wf..."
        status=1
    fi
done

if [ "$status" != 0 ]; then
    echo >&2 "Please consider fixing these inconsistencies before committing..."
fi

exit $status
