#!/bin/bash

WORKFLOWS=".github/workflows/verify.yml"

if git diff --cached go.mod | grep -q '^+go '; then
    gomod=$(go list -m -f '{{.GoVersion}}')
else
    exit 0
fi

status=0
for wf in $WORKFLOWS; do
    workflow=$(grep 'go-version:' $wf | sed 's/^.*: //')
    if [ "$gomod" != "$workflow" ]; then
        echo >&2 "ERROR: inconsistent golang versions, $gomod in go.mod but $workflow in $wf..."
        status=1
    fi
done

if [ "$status" != 0 ]; then
    echo >&2 "Please consider fixing these inconsistencies before committing..."
fi

exit $status
