---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerDeployment
metadata:
  name: cri-rm-extension
type: helm
providerConfig:
  chart: H4sIAAAAAAAAA+1aX2/bNhDPsz4F4aIvA6RIsi0PBgYsS7e2QFAEzVDsbaCls82FEgWScusF/e47UraixHHkOJnTpvw92DR55J14f3gnekZlBgVIH75oKBQThZ9K5sv8+OjJECJGw6H9Rtz+tu1oEIcRkoX96CiMBsN+eESGTyfCdlRKU0nIkRRC30fXNf6dYrZV/6dzKnWwpDl/LA+j4GQw2Kr/eBSh/qMEbWTQN/1RMhglRyR8igfswg+uf1qyTyCN3sdkEXsFzWFMagu4NgkvA4V9pbZkJ+Qd8Jykxj6IFoQVuIWc17NAiUqmoPycFnQGklBFmnUM9duVwZFSin8g1Z6nlyXypGXJWUoNC2+xligMoiD0cKiRsRcFURKEPe+5N+6FYLv/a8hLTjWoR58Eu8f/aBgnA+P/w/7Qxf9DYBf9Z1Byscyh2PM46Ij/qPrR+vzvxwme/3E0HI1c/D8E2vEf46w6XkTeJSuyMXnTaN3LQdOMajr2CKlPiK1ms6JQJU2R7OqKBB+BA1UQfFh3k69fkYrTCXBlViSGcXBZTUAWgPYWMHHcxUWVkJq5EhbM9L9jSgu5PGM503hs2BF7nqhaiE+UV7jyqvNUVIWuxVAoXYpTa0FyqtP5WUuyfWQjZO06q0Vbu2fAb6y/HwcUfLUDBqVkQjK9POVUqQ87TDbPLRcshZM0NXux25xUFJoyJGiE93cwhxosx2zA6oIVKa8yID3b1SNBrYgW2XnF+blARS1vKM+OBWUz2J6XihwTjux6U31y3C2UT3wfjTMzNMYMkOSXKeUKfpzsYpf4vzav1JjXHkdAV/7fj+Km/otiE//jfjR08f8QaMd/lc4hqzgrZsHlzzYQNYfBeTvCPOg8WBjnHZOoSfW8GRcTyt/AlFYcg3XtcDcqjN6aHbEmR6ZCEj2H69qh4bKuVQJXEOyHXfx/dVbQ+qx4eADorP+TpMn/+oPY+P+gP3D+fwjcqP/X3n5xIzn4BtO/5961l4Nd/P/vOfASjSTQ5V7vAjvP/5b/h6PE1H9hEjv/PwSurnxCMphiWt9k5L71UDPCpmRO1bnE8S+kp+Y0Hibj3q2MXNMZaWZgrljoKem9Vr++VrcpsfwSiplC7b4lMC7AXQuO916wyMyPVvO5d/3bwS7+Lyc0fcxFQIf/95Ph2v+jMDbvCWPMA1z+fxC8Ihfnb/7y/2AcTkW5lGw213+iLYxJjGGYXJyck4vfCebftLA/6HTKOEOzMCV3SYslDmTXibl5RSDZpEKXVN4rb7X6GSYThQL/PRJpNmUgx+QEc4E5+HEQep7v+147EbEGRys9xyLgX3slsFGQnHJUHMiPgsMd+UljzCpYG3iQclFl4/syl8flJHfPspcjxV3JkIlDsuKADH2cyN5KUZWWu2/fxNl3WKvblLr3+j1se9AmVjWBYe3jUiZhB4ld+DlZjc1A22/OVN34bN512VZpW3sJ0c1gY9mtutnkldZK3pMRzXKmDCMJMySVbUPa5JVXGgmK2WeYzIW4REOesllVT9pNANOqSjREqIWXsG5u2eAH7ERWKAmpkNmee9Es18mpvrfLmt6b/Ho/9TYX7/U2l2mqgP/fSq5Jb/08RtfT1e7KK2+rcacnrS0lp2XNXgEqXq9EWWy6yZ07mApULSvut1AbOm6ttjKyxwXQ37ADLf97jqP4FB9haliud/aeTUCqzUPkMY+sqom5yraR/M4K+qnq5qc//7fnf4s6n36CP4B01X9Rv/n/z2AU98397yhy9d9BUN/L1Pdlq1Kq426LzsbE1gXGrMvWVc376QehsVZU5srwuZ/LwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHB4aXiP444fGQAUAAA
---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerRegistration
metadata:
  name: cri-rm-extension
spec:
  deployment:
    deploymentRefs:
    - name: cri-rm-extension
  resources:
  - kind: Extension
    type: cri-rm-extension
    globallyEnabled: true
