---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerDeployment
metadata:
  name: cri-rm-extension
type: helm
providerConfig:
  chart: H4sIAAAAAAAAA+1XX2/bNhDPMz/FrXnZikmWHNsB/JbZAVqshYO48GtBS2eZC0VyJOU067rPvpNkJ66KNBhau2jH3wNJHY8nHu8Pj5kVtuydHBQJ4Xw4bHpCt2/G6dkg7Q/7o1FNT5PR6PwEhofdVovKeW4BTqzW/nN8T81/p8ga+0/W3Pr4jpfyEP+oDTwaDB61f3qeduzfH6VnJ5AcYjNd/M/tz41YoHVCqzFs+owb8/CZxEmcshwdOYnxDe0CXqAsIav9BVbawu/VEq1Cj44pXuIYGodi/s7QmKRJkfF6Kdt0xH5rxQMatPG/4bJCd6gE8FT8J4NhJ/7PkmEa4v8YcGvS620dus7wjGK2IUSR1BmX2y7E6o+LNv49lkZySuIHqQT/e/1H/TDUf8dA1/4lV7zA3KLTlc0watLBF14MT+T/9DwZfGz/fhLy/5EQRRH7qAZM2Y1Q+RjmmFn0rETPc+75mAHcF3iRLSOh6OCkbIu7dm57g7x/D/GiLSg6twt8+LCtDGeG/1khc94KVUy38k/hzQx+u4Try6tXF5PLKdwKv4Ypx1KrOXrY/yUsucMcaFBshNOWluvlH5j5tooZw99EAajVq/uOijWpVXOi1UoUr7lpaPva1nhU4wjfcQoZTPcYt+rnuOKV9NsJrpT2zRK3Ewqwiy4XF9zmqNDGmdRV3hOF0pZkPPO2wmdH0aB/UA267vXouk3KpVnznfe9btPQ9Zb967uhM5jVwlzj5te4apSLPiOcnZID1h72ii9REvspncNK6zG5oqUPeg1lOKNnzq0VHrdMsOLS4SezF3tnes9yg2hmrQ8/EHOU9Li6qs/PeVR+oWVV4kRyUd5zfUn8t/k/XtOrrjXd10ose3iq/h+efVr/9wch/x8Dp3DFvacnvAOvoXUBuF0jJdhKyJyyM1DI3FAwupjc8c1aOHCVMdp6GpDbSCikXkLJfbYm7l8pxOuA2SCto+z9QOcqJwEKizZ//2wsrsQ7yuFNlv/plxhmSt5RRm9W1lsCgxakUBizeDp/O/e0NxIx0SVdCLCYzCEX1rG4EL7XtO32Wbz8y/aadkdYF7262X26jeo9CFqSfpWBlZDo2PPY3Rpql/yGWl/WY01y2PN/aMWCW6ErBy+nl/RfY3UdrSwWOfJey04kFm9cpnPshXdTQEBAQEBAQEBAQEBAQEBAQMC3xr8aczFyACgAAA==
  values:
    image:
      tag: v0.0.1
    shoot_namespace: {{ .Values.shoot_namespace }}
---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerRegistration
metadata:
  name: cri-rm-extension
spec:
  deployment:
    deploymentRefs:
    - name: cri-rm-extension
  resources:
  - kind: Extension
    type: cri-rm-extension
    globallyEnabled: true
