---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerDeployment
metadata:
  name: cri-rm-extension
type: helm
providerConfig:
  chart: H4sIAAAAAAAAA+1XS4/bNhDeM3/FNL60QSVb8mMB3wJvgRZt4CBb+BpQ0lhmlyJZkvJmk6a/vaOHd7dKt0ZQ2GkbfgdKGg1Ho3kzt8JW44uTYkK4nM/bK2F4be+T6SxJ5+li0dCTyWJxeQHz06rVoXaeW4ALq7X/O75j7/+jyFv/r3bc+viOV/IU32gcvJjNnvR/cpkM/J8ukukFTE6hzBBfuP+5ERu0Tmi1hH3KuDEPj5N4EiesQEdBYnxLewHfo6wgb+IFttrCj3WGVqFHxxSvcAltQDF/Z+iepEmR82Yr2w/Efu4fD2jR5f+eyxrdqQrAsfyfzOaD/J9O5knI/3PA7ei/3jSp6wzPKWdbQhRJnXPZX0Ku/n/R5b/HykhORfwkk+Cnz390nYf57xwY+r/iipdYWHS6tjlGbTn4h43hSP1PZunA/ym1hFmo/+dAFEWMjeDn9dV6CV5DhmCRYiHHAm6F30HBsdLKoQehyFRStuMccEfPUO6F05axP02RCbsRqljCNeYWPavQ84J7vmQA3Yg4iLE0wrec4g+TnqPvRO/fQ7zpBpNBl4IPH/oJc234rzUy561Q5VX/FZ39grnvxpkl/EYUgIGGDanTcqXVVpQvuWlpj5Vt0ClMieGjJJ3OHlF7JQvc8lr6/gVXSvvWQO4gAeDwny4uuS1QoY1zqetiLEqlLcl45m2Nz1jjisdqPrlvn3Bpdvxg55edOV/37H9h8N6+6afY1xnMGwmu9eJr3LZ/FB11ITGNnmKL7hUZUfQ0TvqJZyhJ8ojstNV6CRm39EAnixzXdGS4tcJjzwRbLh1+9PbFI5vfs9wgmnUXBg/EAiUdVF419nUeld9oWVe4klxU91yfOx/Pja7+xzs61XXheIJvHJv/59OP5/801P+zYASvuPd0hHdN9e9CAG53qCCrhSyoqgJVhBvKYhc3fWInHLjaGG093VDYSCilzijTfb4j7m+pbDUtYo+0j9rHA52rggQoLLsG8rWxuBVvD23mq29iWCt5B1q1OxuVwKAFKRTGLL66fnPtSTcSsdIVdSTYrK6hENaxuBR+3K6d+izO3tlxux4Iu3LcLIdHt1fjB0EZ/V9tYCskOvY8dreG1ozf0Oqr5l6THPb8d9qx4Vbo2sEPV9/Rd43VTYVhsSiQjzt2IrF473Jd4PiLKyYBAQEBAQEBAQEBAQEBAQEBAf86/AGlSXRlACgAAA==
  values:
    image:
      tag: v0.0.1
    shoot_namespace: {{ .Values.shoot_namespace }}
---
apiVersion: core.gardener.cloud/v1beta1
kind: ControllerRegistration
metadata:
  name: cri-rm-extension
spec:
  deployment:
    deploymentRefs:
    - name: cri-rm-extension
  resources:
  - kind: Extension
    type: cri-rm-extension
    globallyEnabled: false
