#!/bin/sh

# set -x

dirpart=packages/src/github.com/intel/cri-interceptor

case $(pwd) in
    */$dirpart*)
        ;;
    *)
        echo "Don't know how: I don't see $dirpart in $(pwd)..."
        return 1
        ;;
esac

dir=$(pwd)
kubedir=${dir%%/github.com*}/k8s.io/kubernetes
kubebin=$kubedir/_output/local/bin/linux/amd64

if [ ! -d "$kubebin" ]; then
    echo "*** You don't seem to have a $kubebin directory."
    return 1
fi

if [ ! -x "$kubebin"/kubelet ]; then
    echo "*** You don't seem to have kubelet in $kubebin (done a make WHAT=cmd/kubelet ?)"
    ls -ls "$kubebin"
    return 1
fi

export PATH="$kubebin:$PATH"
