#!/usr/bin/env python3
#
# Enable containerd NRI plugin

import tomli_w
import toml

data=toml.load("/etc/containerd/config.toml")
((data["plugins"])["io.containerd.nri.v1.nri"])["disable"]=False

with open("/etc/containerd/config.toml", "wb") as f:
    tomli_w.dump(data, f)
