name: Go
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Install golangci-lint
      run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.18.0

    - name: Gofmt
      run: make format

    - name: InstallVFSGenDev
      run: go get -u github.com/shurcooL/vfsgen/cmd/vfsgendev

    - name: Build
      run: make

    - name: Golangci-lint
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        make golangci-lint

    - name: Test
      run: make test

    - name: Codecov report
      run: bash <(curl -s https://codecov.io/bash)
