name: Build and publish devel container images

on:
  push:
    branches: ["master"]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  trivy-scan:
    uses: "./.github/workflows/common-trivy.yaml"
    permissions:
      contents: read
      security-events: write

  publish-images:
    uses: "./.github/workflows/common-build-images.yaml"
    needs: [trivy-scan]
    secrets: inherit
    with:
      publish: true
      image-tag: "devel"
      github-environment: "staging"

