name: Verify PR

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  verify:
    uses: "./.github/workflows/common-verify.yaml"
