name: Verify documentation

on:
  pull_request:
    paths:
      - "docs/**"
      - "Makefile"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  verify-docs:
    uses: "./.github/workflows/common-build-docs.yaml"
